"""Changed size of ssl_certificate to 10000

Revision ID: 360f2452b82f
Revises: 350f6cc3152e
Create Date: 2023-04-11 15:01:07.233903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360f2452b82f'
down_revision = '350f6cc3152e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.alter_column('certificate',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.alter_column('certificate',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###
