"""Added issuer attributes

Revision ID: 50922f01e43f
Revises: 5a4e16a9513e
Create Date: 2023-04-24 11:50:17.071010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50922f01e43f'
down_revision = '5a4e16a9513e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuer_country', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('issuer_state', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('issuer_locality', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('issuer_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('issuer_common_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('issuer_organization_unit', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('issuer_organization_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.drop_column('issuer_organization_name')
        batch_op.drop_column('issuer_organization_unit')
        batch_op.drop_column('issuer_common_name')
        batch_op.drop_column('issuer_email')
        batch_op.drop_column('issuer_locality')
        batch_op.drop_column('issuer_state')
        batch_op.drop_column('issuer_country')

    # ### end Alembic commands ###
