"""Added columns to sslcertificate

Revision ID: 741b145ff12a
Revises: 30c0d487b918
Create Date: 2023-04-17 13:34:02.203731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741b145ff12a'
down_revision = '30c0d487b918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('not_valid_after', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('not_valid_before', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('issuer', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('signature_hash_algorithm', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('subject')
        batch_op.drop_column('signature_hash_algorithm')
        batch_op.drop_column('signature')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('issuer')
        batch_op.drop_column('not_valid_before')
        batch_op.drop_column('not_valid_after')

    # ### end Alembic commands ###
