"""Added name column for sslcertificate table

Revision ID: aa0b924faa2f
Revises: f65da4e97d5f
Create Date: 2023-04-21 10:31:09.025792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0b924faa2f'
down_revision = 'f65da4e97d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
