"""Changed size of ssl_certificate to 10000

Revision ID: c222091d6d74
Revises: 360f2452b82f
Create Date: 2023-04-11 15:02:14.702925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c222091d6d74'
down_revision = '360f2452b82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.alter_column('certificate',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.alter_column('certificate',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###
