"""Added private_key column in certificate

Revision ID: d1eaae1dbb7d
Revises: 50922f01e43f
Create Date: 2023-04-26 11:14:45.972298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1eaae1dbb7d'
down_revision = '50922f01e43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.drop_column('private_key')

    # ### end Alembic commands ###
