"""Added certificate_type in sslcertificate table

Revision ID: d7475ec9caff
Revises: d1eaae1dbb7d
Create Date: 2023-04-26 11:51:27.263405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7475ec9caff'
down_revision = 'd1eaae1dbb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.drop_column('certificate_type')

    # ### end Alembic commands ###
