"""Changed size of signature to 10000

Revision ID: f65da4e97d5f
Revises: 741b145ff12a
Create Date: 2023-04-17 14:57:43.262847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65da4e97d5f'
down_revision = '741b145ff12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.alter_column('signature',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sslcertificate', schema=None) as batch_op:
        batch_op.alter_column('signature',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
